language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

sudo: false

cache:
  directories:
    - $HOME/miniconda

before_install:
 - export MINICONDA=$HOME/miniconda
 - export PATH="$MINICONDA/bin:$PATH"
 - hash -r
 - command -v conda >/dev/null || { wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
   bash miniconda.sh -b -f -p $MINICONDA; }
 - conda config --set always_yes yes
 - conda update conda
 - conda info -a
 - conda install python=$TRAVIS_PYTHON_VERSION
 - conda remove --name mocatest --all
 - conda config --add channels bioconda
 - conda config --add channels r
 - conda config --add channels conda-forge
 - conda env create -q -f environment.yml python=$TRAVIS_PYTHON_VERSION

 - source activate mocatest

 - bash travis/install_meme.sh
 - export PATH="$PATH:$HOME/meme_bin/bin"

install:
  - python setup.py install --single-version-externally-managed --record=/tmp/record.txt 

script: py.test --mpl --cov --cov-report term-missing

after_script:
  - codecov
  - coveralls
  - source deactivate mocatest
  - conda remove --name mocatest --all

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: saketkc
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: saketkc/moca
    condition: $TOXENV == py27
