
sudo: false
language: python

matrix:
  include:
    - python: 2.7

addons:
  apt:
    packages:
      - texlive-latex-base
      - texlive-latex-extra
      - texlive-fonts-recommended
      - texlive-latex-recommended
      - texlive-xetex

after_script:
 - codecov
 - coveralls
 - source deactivate mocadev
 - conda remove --name mocadev --all

before_install:
  - export MINICONDA=$HOME/miniconda
  - export PATH="$MINICONDA/bin:$PATH"
  - hash -r
  - command -v conda >/dev/null || { wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
    -O miniconda.sh; bash miniconda.sh -b -f -p $MINICONDA; }
  - conda config --set always_yes yes
  - conda update conda
  - conda info -a
  - conda install python=$TRAVIS_PYTHON_VERSION
  - conda remove --name mocadev --all || echo 'removed'
  - conda config --add channels bioconda
  - conda config --add channels r
  - conda env create -q -f environment.yml python=$TRAVIS_PYTHON_VERSION
  - source activate mocadev
  - pip install pytest-mpl codecov
  - bash travis/install_meme.sh
  - export PATH="$PATH:$HOME/meme_bin/bin"

install:
  - python setup.py install --single-version-externally-managed --record=/tmp/record.txt

script:
  - moca --help
  - py.test --verbose --mpl --cov=moca --cov-config .coveragerc --cov-report term-missing

cache:
  directories:
    - $HOME/miniconda
    - $HOME/meme_bin

deploy:
  true:
    condition: $TRAVIS_PYTHON_VERSION == 2.7
    repo: saketkc/moca
    tags: true
  distributions: sdist bdist_wheel
  password:
    secure: Fpd8J33Sa/eoQS/Gw7nXv98OHiarNppmzJgIy6Y8GHfrWbioGtk3rfRXhuJYKReB6XE6C9cE95tjFDj3GXae3gCU2T15yvBV95fwv4hkzJBqkVN/khUo9uzTZt+Jx0/0X2sHucmhuQHSxfiBPTOCYS1HxExgn/nd2tS/VIIGP3VN6bJ8YxLVk+R8wv4fFRHKjUvdXeeX1n2N18SS3i1USKsoMesS6wXuht2jwXqdg4YMeHAuEw8D2lxoFCPgJ/rx+rLx3UB+b92GaoeUeAS/3hFokvSP4bUvoAbeFnpzWUkteFt9PegzvKfeNu3vpjkmiki5aNm0dnAUQLhRlLQYQeXzsj/7vI78uqzpWducn21NrumjQ5r2PCVTdkpWPhG8BxDe9C53YuNWuLzA65Q7vdgGjruuQsQWPVeX+eHPrZBCFBAKkNIbxMQYDKWBAuh9Ank5ICcghIrmVh/REnZy8OU3SQs5SGjDUJKnDKOyzfjmvG78Cf6UMMdfjZf+/6Z/AJrytTBYS2mEBEqH0xuCMcdHYRNbEpDZ+K3/YZhwNkvUoZxEk8URAGmVUcZFZFiine4mhlCX1A/vEdGP+jtlYys9CcvSaBMpakLDR0L192fqWnx+isstO0Og7Mh794e4X6z0Fw95MsUOMgDnAV+pk5I0BvV5QxLKOThLmsoDIrU=
  provider: pypi
  user: saketkc
