language: python

env:
  - "2.6"
  - "2.7"

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - libstdc++-4.8-dev
      - ghostscript
cache:
  directories:
    - $HOME/miniconda
    - $HOME/data

before_install:
 - mkdir -p "$HOME/data"
 - export MINICONDA=$HOME/miniconda
 - export PATH="$MINICONDA/bin:$PATH"
 - hash -r
 - command -v conda >/dev/null || { wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
   bash miniconda.sh -b -f -p $MINICONDA; }
 - conda config --set always_yes yes
 - conda update conda
 - conda info -a
 - conda install python=$TRAVIS_PYTHON_VERSION
 - conda remove --name mocatest --all
 - conda config --add channels bioconda
 - conda config --add channels r
 - conda install gcc perl
 - conda env create -q -f environment.yml python=$TRAVIS_PYTHON_VERSION

 - source activate mocatest
 - export MEME_ETC_DIR="$MINICONDA/envs/mocatest/etc"
 - conda install meme -c saketkc

install:
  - python setup.py install --single-version-externally-managed --record=/tmp/record.txt

script: nosetests -v --with-coverage

after_script:
  - codecov
  - coveralls
  - source deactivate mocatest
  - conda remove --name mocatest --all

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: saketkc
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: saketkc/moca
    condition: $TOXENV == py27
