name: mocaweb
dependencies:
- flask=0.10.1=py27_1
- future=0.15.2=py27_0
- itsdangerous=0.24=py27_0
- jinja2=2.8=py27_1
- markupsafe=0.23=py27_2
- openssl=1.0.2h=0
- pip=8.1.1=py27_1
- pymongo=3.0.3=py27_0
- python=2.7.11=0
- readline=6.2=2
- requests=2.10.0=py27_0
- setuptools=21.2.1=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- werkzeug=0.11.9=py27_0
- wheel=0.29.0=py27_0
- zlib=1.2.8=3
- pip:
  - aniso8601==1.1.0
  - flask-restful==0.3.5
  - python-dateutil==2.5.3
  - pytz==2016.4
  - six==1.10.0

